name: publish test harness to nuget
on:
  release:
    types: [published]
      
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
    - name: Build
      run: dotnet build -c Release
      working-directory: ./src/HaKafkaNet.TestHarness
    - name: Test
      run: dotnet test -c Release --no-build
      working-directory: ./src/HaKafkaNet.TestHarness
    - name: Pack nugets
      run: dotnet pack -c Release --no-build --output .
      working-directory: ./src/HaKafkaNet.TestHarness
    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGET}} --source https://api.nuget.org/v3/index.json
      working-directory: ./src/HaKafkaNet.TestHarness